language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

branches:
  only:
  - develop

install:
  - python setup.py install

script:
  - pytest

matrix:
  allow_failures:
    - python: "3.7"